app: fazeapp
service: bot-army-service

	
disabledDeprecations:
  - CODE_1 # To disable specific deprecation with code "CODE_1"
  - '*' # To disable all deprecation messages
frameworkVersion: '3'

custom:
  wsgi:
    app: app.app
  stage: ${self:provider.stage}
  corsInfo:
    origin: "*"
    headers:
      - Content-Type
      - X-Amz-Date
      - Authorization
      - X-Api-Key
      - X-Amz-Security-Token
      - X-Amz-User-Agent
      - sessionkey
      - x_auth_token
      - x-requested-with
    allowCredentials: true

provider:
  name: aws
  runtime: python3.8
  timeout: 300
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-south-1'}
  # profile: fazeStage
  # endpointType: PRIVATE
  versionFunctions: false
  resourcePolicy:
  - Effect: Allow
    Principal: "*"
    Action: execute-api:Invoke
    Resource: "*"
  # vpcEndpointIds:
  #   - ${opt:vpcEndpointIds}
  # vpc:
  #   securityGroupIds:
  #     - ${opt:securityGroup}
  #   subnetIds:
  #     - ${opt:subnetId}
  apiGateway:
    binaryMediaTypes:
    - "multipart/form-data"
  environment:
    stage: ${self:provider.stage}
    region: ${self:provider.region}
    # secretConfig: ${ssm:/config-challenge-${self:provider.stage}~true}
  iam:
    RoleStatements:
      - Effect: "Allow"
        Action:
          - "sqs:*"
          - "s3:*"
        Resource:
          - "arn:aws:sqs:${self:provider.region}:*:*"
          - "arn:aws:s3:::*"


functions:

  routeHandler:
    handler: wsgi_handler.handler
    timeout: 900
    memorySize: 5120
    events:
      - http:
        path: /
        method: ANY
      - http:
        path: /{proxy+}
        method: ANY
    
  createUserQueueHandler:
    handler: controllers/botArmyController.createUserQueueHandler
    timeout: 900
    memorySize: 10240
    reservedConcurrency: 10 # scale to max 10 workers
    events:
      - sqs:
        batchSize: 1
        arn:
          Fn::GetAtt:
            - createUserQueue
            - Arn

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-lift


package:
  patterns:
  - '!node_modules/**'

resources:
  Resources:
    createUserQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: createUserQueue
        VisibilityTimeout: 900
